### ISSUE TITLE
ModuleNotFoundError: No module named 'jack_mixer_c'

### ISSUE THREAD

**Issue by mxa** [jack-mixer/jack_mixer#110]
After compiling the source I can't run jack mixer.
```

$ jack_mixer
Traceback (most recent call last):
  File "/usr/local/bin/jack_mixer", line 40, in <module>
    import jack_mixer_c
ModuleNotFoundError: No module named 'jack_mixer_c'
```

**Comment by SpotlightKid** [comment]
Please read the wiki page again (see Step 3).

**Comment by mxa** [comment]
followed it exactly:

```
max@klapprechner:~/Code/jack_mixer$ sed -i -e   's|import sys|import sys\nimport sysconfig\nsys.path.insert(0, sysconfig.get_path("purelib"))|'   jack_mixer/__main__.py
max@klapprechner:~/Code/jack_mixer$ sudo meson install -C builddir
ninja: Entering directory `builddir'
ninja: no work to do.
Installing src/jack_mix_box to /usr/bin
Installing jack_mixer/_jack_mixer.cpython-38-x86_64-linux-gnu.so to /usr/lib/python3.8/site-packages/jack_mixer
Installing docs/jack_mixer.1 to /usr/share/man/man1
Installing /home/max/Code/jack_mixer/jack_mixer/abspeak.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/app.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/channel.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/gui.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/__main__.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/meter.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/nsmclient.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/preferences.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/scale.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/serialization.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/serialization_xml.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/slider.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/styling.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/builddir/jack_mixer/version.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/__main__.py to /usr/bin
Installing /home/max/Code/jack_mixer/data/jack_mixer.desktop to /usr/share/applications
Installing /home/max/Code/jack_mixer/data/art/16x16/jack_mixer.png to /usr/share/icons/hicolor/16x16/apps
Installing /home/max/Code/jack_mixer/data/art/22x22/jack_mixer.png to /usr/share/icons/hicolor/22x22/apps
Installing /home/max/Code/jack_mixer/data/art/24x24/jack_mixer.png to /usr/share/icons/hicolor/24x24/apps
Installing /home/max/Code/jack_mixer/data/art/32x32/jack_mixer.png to /usr/share/icons/hicolor/32x32/apps
Installing /home/max/Code/jack_mixer/data/art/48x48/jack_mixer.png to /usr/share/icons/hicolor/48x48/apps
Installing /home/max/Code/jack_mixer/data/art/scalable/jack_mixer.svg to /usr/share/icons/hicolor/scalable/apps
Running custom install script '/home/max/Code/jack_mixer/meson_postinstall.py'
Updating icon cache...
Compiling Python module to bytecode...
Listing '/usr/lib/python3.8/site-packages/jack_mixer'...
Compiling '/usr/lib/python3.8/site-packages/jack_mixer/__main__.py'...
***   File "/usr/lib/python3.8/site-packages/jack_mixer/__main__.py", line 8
    sys.path.insert(0, sysconfig.get_path("purelib"))config
                                                     ^
SyntaxError: invalid syntax

```

**Comment by SpotlightKid** [comment]
See #111.

**Comment by mxa** [comment]
issue is not resolved.
Here is the full install process:
```

rm -r jack_mixer/
$ sudo apt-get install \
>     build-essential \
>     jackd2 \
>     libglib2.0-dev \
>     libjack-jackd2-dev \
>     meson \
>     pkgconf \
>     python-gi \
>     python-xdg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-gi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-gi' has no installation candidate
E: Unable to locate package python-xdg

$ sudo apt install python3-gi 
Reading package lists... Done                                                                                 
Building dependency tree       
Reading state information... Done
python3-gi is already the newest version (3.38.0-1).
python3-gi set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ sudo apt install python3-xdg
Reading package lists... Done                                                                                 
Building dependency tree       
Reading state information... Done
python3-xdg is already the newest version (0.26-3ubuntu1).

$ sudo apt-get install cython3 git python3-docutils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.27.0-1ubuntu1).
python3-docutils is already the newest version (0.16+dfsg-3).
cython3 is already the newest version (0.29.21-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ git clone https://github.com/jack-mixer/jack_mixer
Cloning into 'jack_mixer'...
remote: Enumerating objects: 198, done.
remote: Counting objects: 100% (198/198), done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 1946 (delta 116), reused 151 (delta 75), pack-reused 1748
Receiving objects: 100% (1946/1946), 544.29 KiB | 5.61 MiB/s, done.
Resolving deltas: 100% (1323/1323), done.

$ cd jack_mixer/ 
$ sed -i -e \
>   's|import sys|import sys\nimport sysconfig\nsys.path.insert(0, sysconfig.get_path("purelib"))|' \
>   jack_mixer/__main__.py

$ meson setup builddir --prefix=/usr --buildtype=release
The Meson build system
Version: 0.55.3
Source dir: /home/max/Code/jack_mixer
Build dir: /home/max/Code/jack_mixer/builddir
Build type: native build
Project name: jack_mixer
Project version: 15
C compiler for the host machine: cc (gcc 10.2.0 "cc (Ubuntu 10.2.0-13ubuntu1) 10.2.0")
C linker for the host machine: cc ld.bfd 2.35.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Run-time dependency glib-2.0 found: YES 2.66.1
Library m found: YES
Run-time dependency jack found: YES 1.9.14
Dependency jack found: YES 1.9.14 (cached)
Program python3 (gi, cairo, xdg) found: YES (/usr/bin/python3) modules: gi, cairo, xdg
Program cython3 found: YES
Program meson_dist_cython.py found: YES (/home/max/Code/jack_mixer/src/meson_dist_cython.py)
Dependency python found: YES (pkgconfig)
Configuring version.py using configuration
Program rst2man found: YES
Configuring jack_mixer.1.rst using configuration
Program meson_dist_rst2man.py found: YES (/home/max/Code/jack_mixer/docs/meson_dist_rst2man.py)
Program meson_postinstall.py found: YES (/home/max/Code/jack_mixer/meson_postinstall.py)
Build targets in project: 4

jack_mixer 15

  Configuration
        Build jack_mixer GUI: True
           JACK MIDI support: True
    Debug messages (verbose): False
             Build for wheel: False

Found ninja-1.10.0 at /usr/bin/ninja

$ ninja -C builddir
ninja: Entering directory `builddir'
[12/12] Linking target jack_mixer/_jack_mixer.cpython-38-x86_64-linux-gnu.so

$ sudo ninja -C builddir install
ninja: Entering directory `builddir'
[0/1] Installing files.
Installing src/jack_mix_box to /usr/bin
Installing jack_mixer/_jack_mixer.cpython-38-x86_64-linux-gnu.so to /usr/lib/python3.8/site-packages/jack_mixer
Installing docs/jack_mixer.1 to /usr/share/man/man1
Installing /home/max/Code/jack_mixer/jack_mixer/abspeak.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/app.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/channel.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/gui.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/__main__.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/meter.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/nsmclient.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/preferences.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/scale.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/serialization.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/serialization_xml.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/slider.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/styling.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/builddir/jack_mixer/version.py to /usr/lib/python3.8/site-packages/jack_mixer
Installing /home/max/Code/jack_mixer/jack_mixer/__main__.py to /usr/bin
Installing /home/max/Code/jack_mixer/data/jack_mixer.desktop to /usr/share/applications
Installing /home/max/Code/jack_mixer/data/art/16x16/jack_mixer.png to /usr/share/icons/hicolor/16x16/apps
Installing /home/max/Code/jack_mixer/data/art/22x22/jack_mixer.png to /usr/share/icons/hicolor/22x22/apps
Installing /home/max/Code/jack_mixer/data/art/24x24/jack_mixer.png to /usr/share/icons/hicolor/24x24/apps
Installing /home/max/Code/jack_mixer/data/art/32x32/jack_mixer.png to /usr/share/icons/hicolor/32x32/apps
Installing /home/max/Code/jack_mixer/data/art/48x48/jack_mixer.png to /usr/share/icons/hicolor/48x48/apps
Installing /home/max/Code/jack_mixer/data/art/scalable/jack_mixer.svg to /usr/share/icons/hicolor/scalable/apps
Running custom install script '/home/max/Code/jack_mixer/meson_postinstall.py'
Updating icon cache...
Compiling Python module to bytecode...
Listing '/usr/lib/python3.8/site-packages/jack_mixer'...
Compiling '/usr/lib/python3.8/site-packages/jack_mixer/__main__.py'...
Compiling '/usr/lib/python3.8/site-packages/jack_mixer/abspeak.py'...
Compiling '/usr/lib/python3.8/site-packages/jack_mixer/app.py'...
Compiling '/usr/lib/python3.8/site-packages/jack_mixer/channel.py'...
Compiling '/usr/lib/python3.8/site-packages/jack_mixer/gui.py'...
Compiling '/usr/lib/python3.8/site-packages/jack_mixer/meter.py'...
Compiling '/usr/lib/python3.8/site-packages/jack_mixer/nsmclient.py'...
Compiling '/usr/lib/python3.8/site-packages/jack_mixer/preferences.py'...
Compiling '/usr/lib/python3.8/site-packages/jack_mixer/scale.py'...
Compiling '/usr/lib/python3.8/site-packages/jack_mixer/serialization.py'...
Compiling '/usr/lib/python3.8/site-packages/jack_mixer/serialization_xml.py'...
Compiling '/usr/lib/python3.8/site-packages/jack_mixer/slider.py'...
Compiling '/usr/lib/python3.8/site-packages/jack_mixer/styling.py'...
Compiling '/usr/lib/python3.8/site-packages/jack_mixer/version.py'...
max@klapprechner:~/Code/jack_mixer$ jack_mixer
Traceback (most recent call last):
  File "/usr/local/bin/jack_mixer", line 40, in <module>
    import jack_mixer_c
ModuleNotFoundError: No module named 'jack_mixer_c'
```

**Comment by SpotlightKid** [comment]
Fixed the `python3-gi` and `python3-xdg` package names in the install instructions.

Can you show the contents of `/usr/bin/jack_mixer` after installation?

Also, can you try running `jack_mixer` again *after* you changed out of the git checkout (e.g. into your home dir)?

**Comment by mxa** [comment]
ok. Sorry `/usr/bin/jack_mixer` is a binary whcih I can't cd into.
The output of `jack_mixer` is the same, wherever I am in the directory,

**Comment by SpotlightKid** [comment]
> Sorry /usr/bin/jack_mixer is a binary which I can't cd into.

No, it's just a short Python script. I wanted to see the content of the script.

    cat /usr/bin/jack_mixer

**Comment by mxa** [comment]
```
#!/usr/bin/env python3

import sys
import sysconfig
sys.path.insert(0, sysconfig.get_path("purelib"))

from jack_mixer.app import main

if __name__ == "__main__":
    sys.exit(main() or 0)

```

**Comment by SpotlightKid** [comment]
Ok, so it seems that Ubuntu 20.10 is different than 20.04 in that probably `sysconfig.get_path("purelib")` return something else.

I'll set up a virtual machine when I have time an test this. In the meantime, could you show me the output of

    python3 -c 'import sys; print(sys.path)'

and

    python3 -c 'import sysconfig; print(sysconfig.get_paths(scheme="posix_prefix"))'

?

**Comment by mxa** [comment]
> ```
> python3 -c 'import sys; print(sys.path)'
> ```

`['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/max/.local/lib/python3.8/site-packages`

> ```
> python3 -c 'import sysconfig; print(sysconfig.get_paths(scheme="posix_prefix"))'
> ```

`{'stdlib': '/usr/lib/python3.8', 'platstdlib': '/usr/lib/python3.8', 'purelib': '/usr/lib/python3.8/site-packages', 'platlib': '/usr/lib/python3.8/site-packages', 'include': '/usr/include/python3.8', 'platinclude': '/usr/include/python3.8', 'scripts': '/usr/bin', 'data': '/usr'}`

**Comment by SpotlightKid** [comment]
Oh, I overlooked something in your install log above. You still have `/usr/local/bin/jack_mixer` from a previous failed install attempt. Please delete it and also `/usr/local/lib/python3.8/site-packages/jack_mixer`, if it exists. Then, make sure that `which jack_mixer` outputs `/usr/bin/jack_mixer` again and then run `jack_mixer` in a terminal or start it from the menu.

**Comment by mxa** [comment]
Yay! Thanks.

**Comment by SpotlightKid** [comment]
That was hard work ;) Thanks for sticking with it.

I've tried to even out some sinks in the installation instructions, which you uncovered.

The sad truth though is, that Debian/Ubuntu makes installing Python programs and packages unnecessarily hard.

**Comment by mxa** [comment]
Looks so shiny! I'm happy this invaluable tool is back and looking good.
