### ISSUE TITLE
Add MIDI channel to control changes dialog

### ISSUE THREAD

**Issue by lazzarello** [jack-mixer/jack_mixer#156]
I have a Korg nanoKontrol hardware surface. It has a "mixer mode" preset in hardware where all the 9 faders transmit CC 7 on channels 1-9. This doesn't work with jack mixer, so adding a "MIDI channel" option to the control changes dialog seems like a reasonable compromise.

Modifying the dynamic MIDI learn system seems more complicated, though it would be nice if it stored the channel byte and the CC byte when the hardware device did a wiggle.

I'm new to cython but I'm hacking my way through UI changes right now.

**Comment by SpotlightKid** [comment]
Thanks for the suggestion. The MIDI control feature needs a general overhaul. I'd like for jack_mixer to be able to be controlled via all types of MIDI messages, with configurable channels and value thresholds (e.g. for on/off elements).

I'll look favourably on a PR, which adds MIDI channel awareness, but this whole functionality might be reworked again in the midterm.

**Comment by lazzarello** [comment]
Thanks for the reply. I made some progress last night. I have a GUI element for channel like so 

![image](https://user-images.githubusercontent.com/3917/151058892-75c719fa-bf21-4675-835c-3fcfa38f4dd4.png)

and I think I hit the cython wall because I can't get rid of this exception when adding the channel.

```
lee@wendy:~/funsrc/jack_mixer$ ./tools/jack_mixer.sh 
Traceback (most recent call last):
  File "/home/lee/funsrc/jack_mixer/jack_mixer/app.py", line 804, in on_add_input_channel
    return self.on_add_channel("input", _("Input"))
  File "/home/lee/funsrc/jack_mixer/jack_mixer/app.py", line 799, in on_add_channel
    (self.add_channel if inout == "input" else self.add_output_channel)(**result)
TypeError: add_channel() got an unexpected keyword argument 'midi_channel'
```
I've never worked with cython before but it looks like I need to add some arguments and types to _jack_mixer.pxd and _jack_mixer.pyx so this value is recognized as a kwarg?
