### ISSUE TITLE
Cannot add new channel / AttributeError: 'NewOutputChannelDialog' object has no attribute 'minus_inf'

### ISSUE THREAD

**Issue by mxmilkiib** [jack-mixer/jack_mixer#39]
Terminal output is 
```
Traceback (most recent call last):
  File "/usr/bin/jack_mixer", line 353, in on_add_output_channel
    result = dialog.get_result()
  File "/usr/bin/../share/jack_mixer/channel.py", line 1105, in get_result
    'value': self.minus_inf.get_active()
AttributeError: 'NewOutputChannelDialog' object has no attribute 'minus_inf'
```

**Comment by dsheeler** [comment]
This should be fixed here f93cc764dd491e609f4052474441463b87e09830
