### ISSUE TITLE
jack_mixer_c.so installed to wrong directory on Debian/Ubuntu

### ISSUE THREAD

**Issue by Houston4444** [jack-mixer/jack_mixer#47]
Hi !
I don't arrive to run jack_mixer under Ubuntu 18.04 + KxStudio packages.

here the logs:

./autogen.sh
```
$ ./autogen.sh 
+ mkdir -p config
+ aclocal -I config -I m4
configure.ac:66: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2601: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2617: AC_COMPILE_IFELSE is expanded from...
m4/jack.m4:4: AC_JACK_MIDI_NFRAMES_CHECK is expanded from...
configure.ac:66: the top level
configure.ac:66: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2601: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2617: AC_COMPILE_IFELSE is expanded from...
m4/jack.m4:4: AC_JACK_MIDI_NFRAMES_CHECK is expanded from...
configure.ac:66: the top level
+ libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
+ autoheader
configure.ac:66: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2601: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2617: AC_COMPILE_IFELSE is expanded from...
m4/jack.m4:4: AC_JACK_MIDI_NFRAMES_CHECK is expanded from...
configure.ac:66: the top level
+ automake --foreign --add-missing --copy
configure.ac:66: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2601: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2617: AC_COMPILE_IFELSE is expanded from...
m4/jack.m4:4: AC_JACK_MIDI_NFRAMES_CHECK is expanded from...
configure.ac:66: the top level
configure.ac:35: installing 'config/compile'
configure.ac:37: installing 'config/config.guess'
configure.ac:37: installing 'config/config.sub'
configure.ac:26: installing 'config/install-sh'
configure.ac:26: installing 'config/missing'
Makefile.am: installing 'config/depcomp'
+ autoconf
configure.ac:66: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2601: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2617: AC_COMPILE_IFELSE is expanded from...
m4/jack.m4:4: AC_JACK_MIDI_NFRAMES_CHECK is expanded from...
configure.ac:66: the top level
+ cd /home/houston/codes_sources/jackckmixer/jack_mixer
+ test -n 
+ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for JACKMIXER... yes
checking for JACK_MIDI... yes
checking for OLD_JACK_MIDI... no
checking whether JACK MIDI functions need nframes parameter... no
checking for a Python interpreter with version >= 3.5... python3
checking for python3... /usr/bin/python3
checking for python3 version... 3.6
checking for python3 platform... linux
checking for python3 script directory... ${prefix}/lib/python3.6/site-packages
checking for python3 extension module directory... ${exec_prefix}/lib/python3.6/site-packages
checking for headers required to compile python extensions... found
checking for python module gi... yes
checking for python module cairo... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating data/Makefile
config.status: creating data/art/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

**********************************************************************

Prefix:            /usr/local
Python dir:        ${prefix}/lib/python3.6/site-packages

MIDI support:      yes

**********************************************************************

```

make
```
$ make
make  all-recursive
make[1] : on entre dans le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer »
Making all in data
make[2] : on entre dans le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data »
Making all in art
make[3] : on entre dans le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data/art »
make[3]: rien à faire pour « all ».
make[3] : on quitte le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data/art »
make[3] : on entre dans le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data »
make[3]: rien à faire pour « all-am ».
make[3] : on quitte le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data »
make[2] : on quitte le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data »
make[2] : on entre dans le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer »
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I/usr/include/python3.6  -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -D_GNU_SOURCE -Wall -fno-strict-aliasing  -g -O2 -MT jack_mixer.lo -MD -MP -MF .deps/jack_mixer.Tpo -c -o jack_mixer.lo jack_mixer.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/python3.6 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -D_GNU_SOURCE -Wall -fno-strict-aliasing -g -O2 -MT jack_mixer.lo -MD -MP -MF .deps/jack_mixer.Tpo -c jack_mixer.c  -fPIC -DPIC -o .libs/jack_mixer.o
mv -f .deps/jack_mixer.Tpo .deps/jack_mixer.Plo
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I/usr/include/python3.6  -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -D_GNU_SOURCE -Wall -fno-strict-aliasing  -g -O2 -MT log.lo -MD -MP -MF .deps/log.Tpo -c -o log.lo log.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/python3.6 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -D_GNU_SOURCE -Wall -fno-strict-aliasing -g -O2 -MT log.lo -MD -MP -MF .deps/log.Tpo -c log.c  -fPIC -DPIC -o .libs/log.o
mv -f .deps/log.Tpo .deps/log.Plo
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I/usr/include/python3.6  -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -D_GNU_SOURCE -Wall -fno-strict-aliasing  -g -O2 -MT scale.lo -MD -MP -MF .deps/scale.Tpo -c -o scale.lo scale.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/python3.6 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -D_GNU_SOURCE -Wall -fno-strict-aliasing -g -O2 -MT scale.lo -MD -MP -MF .deps/scale.Tpo -c scale.c  -fPIC -DPIC -o .libs/scale.o
mv -f .deps/scale.Tpo .deps/scale.Plo
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I/usr/include/python3.6  -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -D_GNU_SOURCE -Wall -fno-strict-aliasing  -g -O2 -MT jack_mixer_c.lo -MD -MP -MF .deps/jack_mixer_c.Tpo -c -o jack_mixer_c.lo jack_mixer_c.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/python3.6 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -D_GNU_SOURCE -Wall -fno-strict-aliasing -g -O2 -MT jack_mixer_c.lo -MD -MP -MF .deps/jack_mixer_c.Tpo -c jack_mixer_c.c  -fPIC -DPIC -o .libs/jack_mixer_c.o
mv -f .deps/jack_mixer_c.Tpo .deps/jack_mixer_c.Plo
/bin/bash ./libtool  --tag=CC   --mode=link gcc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -D_GNU_SOURCE -Wall -fno-strict-aliasing  -g -O2 -module -avoid-version  -o jack_mixer_c.la -rpath /usr/local/lib/python3.6/site-packages jack_mixer.lo log.lo scale.lo jack_mixer_c.lo -lglib-2.0 -ljack 
libtool: link: gcc -shared  -fPIC -DPIC  .libs/jack_mixer.o .libs/log.o .libs/scale.o .libs/jack_mixer_c.o   -lglib-2.0 -ljack  -g -O2   -Wl,-soname -Wl,jack_mixer_c.so -o .libs/jack_mixer_c.so
libtool: link: ( cd ".libs" && rm -f "jack_mixer_c.la" && ln -s "../jack_mixer_c.la" "jack_mixer_c.la" )
gcc -DHAVE_CONFIG_H -I.  -I/usr/include/python3.6  -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -MT jack_mix_box-jack_mix_box.o -MD -MP -MF .deps/jack_mix_box-jack_mix_box.Tpo -c -o jack_mix_box-jack_mix_box.o `test -f 'jack_mix_box.c' || echo './'`jack_mix_box.c
mv -f .deps/jack_mix_box-jack_mix_box.Tpo .deps/jack_mix_box-jack_mix_box.Po
gcc -DHAVE_CONFIG_H -I.  -I/usr/include/python3.6  -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -MT jack_mix_box-jack_mixer.o -MD -MP -MF .deps/jack_mix_box-jack_mixer.Tpo -c -o jack_mix_box-jack_mixer.o `test -f 'jack_mixer.c' || echo './'`jack_mixer.c
mv -f .deps/jack_mix_box-jack_mixer.Tpo .deps/jack_mix_box-jack_mixer.Po
gcc -DHAVE_CONFIG_H -I.  -I/usr/include/python3.6  -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -MT jack_mix_box-scale.o -MD -MP -MF .deps/jack_mix_box-scale.Tpo -c -o jack_mix_box-scale.o `test -f 'scale.c' || echo './'`scale.c
mv -f .deps/jack_mix_box-scale.Tpo .deps/jack_mix_box-scale.Po
gcc -DHAVE_CONFIG_H -I.  -I/usr/include/python3.6  -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -MT jack_mix_box-log.o -MD -MP -MF .deps/jack_mix_box-log.Tpo -c -o jack_mix_box-log.o `test -f 'log.c' || echo './'`log.c
mv -f .deps/jack_mix_box-log.Tpo .deps/jack_mix_box-log.Po
/bin/bash ./libtool  --tag=CC   --mode=link gcc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2   -o jack_mix_box jack_mix_box-jack_mix_box.o jack_mix_box-jack_mixer.o jack_mix_box-scale.o jack_mix_box-log.o -lglib-2.0 -ljack -lm 
libtool: link: gcc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -o jack_mix_box jack_mix_box-jack_mix_box.o jack_mix_box-jack_mixer.o jack_mix_box-scale.o jack_mix_box-log.o  -lglib-2.0 -ljack -lm
make[2] : on quitte le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer »
make[1] : on quitte le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer »
```

sudo make install
```
$ sudo make install
Making install in data
make[1] : on entre dans le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data »
Making install in art
make[2] : on entre dans le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data/art »
make[3] : on entre dans le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data/art »
make[3]: rien à faire pour « install-exec-am ».
 /bin/mkdir -p '/usr/local/share/icons/hicolor/16x16/apps'
 /usr/bin/install -c -m 644 16x16/jack_mixer.png '/usr/local/share/icons/hicolor/16x16/apps'
 /bin/mkdir -p '/usr/local/share/icons/hicolor/22x22/apps'
 /usr/bin/install -c -m 644 22x22/jack_mixer.png '/usr/local/share/icons/hicolor/22x22/apps'
 /bin/mkdir -p '/usr/local/share/icons/hicolor/24x24/apps'
 /usr/bin/install -c -m 644 24x24/jack_mixer.png '/usr/local/share/icons/hicolor/24x24/apps'
 /bin/mkdir -p '/usr/local/share/icons/hicolor/32x32/apps'
 /usr/bin/install -c -m 644 32x32/jack_mixer.png '/usr/local/share/icons/hicolor/32x32/apps'
 /bin/mkdir -p '/usr/local/share/icons/hicolor/48x48/apps'
 /usr/bin/install -c -m 644 48x48/jack_mixer.png '/usr/local/share/icons/hicolor/48x48/apps'
 /bin/mkdir -p '/usr/local/share/icons/hicolor/scalable/apps'
 /usr/bin/install -c -m 644 scalable/jack_mixer.svg '/usr/local/share/icons/hicolor/scalable/apps'
make  install-data-hook
make[4] : on entre dans le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data/art »
Updating Gtk icon cache.
gtk-update-icon-cache: Cache file created successfully.
make[4] : on quitte le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data/art »
make[3] : on quitte le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data/art »
make[2] : on quitte le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data/art »
make[2] : on entre dans le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data »
make[3] : on entre dans le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data »
make[3]: rien à faire pour « install-exec-am ».
 /bin/mkdir -p '/usr/local/share/applications'
 /usr/bin/install -c -m 644 jack_mixer.desktop '/usr/local/share/applications'
make[3] : on quitte le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data »
make[2] : on quitte le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data »
make[1] : on quitte le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer/data »
make[1] : on entre dans le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer »
make[2] : on entre dans le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer »
 /bin/mkdir -p '/usr/local/bin'
  /bin/bash ./libtool   --mode=install /usr/bin/install -c jack_mix_box '/usr/local/bin'
libtool: install: /usr/bin/install -c jack_mix_box /usr/local/bin/jack_mix_box
 /bin/mkdir -p '/usr/local/bin'
 /usr/bin/install -c ./jack_mixer.py '/usr/local/bin'
 /bin/mkdir -p '/usr/local/lib/python3.6/site-packages'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   jack_mixer_c.la '/usr/local/lib/python3.6/site-packages'
libtool: install: /usr/bin/install -c .libs/jack_mixer_c.so /usr/local/lib/python3.6/site-packages/jack_mixer_c.so
libtool: install: /usr/bin/install -c .libs/jack_mixer_c.lai /usr/local/lib/python3.6/site-packages/jack_mixer_c.la
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /usr/local/lib/python3.6/site-packages
----------------------------------------------------------------------
Libraries have been installed in:
   /usr/local/lib/python3.6/site-packages

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make  install-exec-hook
make[3] : on entre dans le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer »
ln -vfs jack_mixer.py /usr/local/bin/jack_mixer
'/usr/local/bin/jack_mixer' -> 'jack_mixer.py'
make[3] : on quitte le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer »
 /bin/mkdir -p '/usr/local/share/jack_mixer'
 /usr/bin/install -c -m 644 abspeak.py channel.py gui.py meter.py scale.py serialization.py serialization_xml.py slider.py preferences.py nsmclient.py '/usr/local/share/jack_mixer'
make[2] : on quitte le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer »
make[1] : on quitte le répertoire « /home/houston/codes_sources/jackckmixer/jack_mixer »
```

run the program
```
$ jack_mixer
Traceback (most recent call last):
  File "/usr/local/bin/jack_mixer", line 39, in <module>
    import jack_mixer_c
ModuleNotFoundError: No module named 'jack_mixer_c'
```

**Comment by dsheeler** [comment]
I think that means it's not finding a python library jack_mixer installs. I'm guessing your python library path doesn't include /usr/local python modules, but I don't know how to make that work. If you could try to reconfigure with 

./configure --prefix=/usr

that might work. Or figure out how to make your python module path include things installed to /usr/local.

**Comment by Houston4444** [comment]
with ./configure --prefix=/usr it doesn't works too, but it is more verbose
```
$ /usr/bin/jack_mixer
Traceback (most recent call last):
  File "/usr/bin/jack_mixer", line 39, in <module>
    import jack_mixer_c
ModuleNotFoundError: No module named 'jack_mixer_c'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 154, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/var/crash/_usr_bin_jack_mixer.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/jack_mixer", line 39, in <module>
    import jack_mixer_c
ModuleNotFoundError: No module named 'jack_mixer_c'
```

**Comment by dsheeler** [comment]
Before you reconfigure, you should probably run

sudo make uninstall

**Comment by Houston4444** [comment]
No I have done it.

**Comment by Houston4444** [comment]
I precise that once installed, there is no file /usr/share/jack_mixer/jack_mixer_c.py

```$ ls /usr/share/jack_mixer/
abspeak.py  channel.py  gui.py  meter.py  nsmclient.py  preferences.py  scale.py  serialization.py  serialization_xml.py  slider.py
```

**Comment by dsheeler** [comment]
I think that ends up somewhere like this: /usr/lib/python3.8/site-packages/jack_mixer_c.so. That's it on my system. Maybe google finding python c interface files to see why you're not finding it

**Comment by dsheeler** [comment]
I am on a walk right now so I can't be as helpful as I want right now ;)

**Comment by Houston4444** [comment]
don't worry, Have a good walk ! That's is nice enough to answer ;)
I don't find such file , I'll try later.

**Comment by SpotlightKid** [comment]
Since you have Python 3.6, if you use `--prefix=/usr`, `jack_mixer_c.so` should end up in `/usr/lib/python3.6/site-packages`. With `--prefix=/usr/local` (the default) it ends up in `/usr/local/lib/python3.6/site-packages`.

With a normal Python 3.6 installation, `import jack_mixer_c` should find the module in either place. But Debian/Ubuntu f*cks with the Python search path in ways, which are hard to fathom.

Can you do the following and report the output here?

    python3 -c 'import sys; print(sys.path)'

**Comment by Houston4444** [comment]
thanks.
`python3 -c 'import sys; print(sys.path)'` returns:
`['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/houston/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']`

**Comment by SpotlightKid** [comment]
This explains, why `jack_mixer` is unable to import `jack_mixer_c`, since neither `/usr/lib/python3.6/site-packages` nor `/usr/local/lib/python3.6/site-packages` are in `sys.path` on Debian/Ubuntu (which are normally the standard locations for third-party packages with official Python).

Debian/Ubuntu patch the distutils module in their Python versions, so Python packages, which use it for installation, get installed to `/usr/lib/python3/dist-packages`. But jack_mixer uses autotools for building & installation, which thinks that Python modules should be installed into `/usr/lib/python3.6/site-packages`, as normal. TBH, I am not sure whether that is due to the way autotools is set up / used in our project, or if Debian autotools does not handle this situation correctly in general. AFAICS, the `configure.ac` file just uses the `AM_PATH_PYTHON` macro to find out the Python `site-packages` directory path. Unfortunately, there does not seem to be a way to overwrite this path when calling `configure`.

My guess is that Debian solves this on the packaging level, i.e. when a deb package is built, which installs something to `site-packages`, the packaging script copies it to `/usr/lib/python3/dist-packages`.

We have a branch where autotools is replaced with Python setuptools and meson, and my intention is for that to become the default in the future, but it is not there yet.

To cut a long story short, at the moment I can only recommend copying `/usr/lib/python3.6/site-packages/jack_mixer_c.so` to `/usr/lib/python3/dist-packages` manually after installation. Or wait for `jack_mixer` to be packaged for KXStudio.

**Comment by SpotlightKid** [comment]
For reference, here's the (WIP) PR for the meson/setuptools branch: #29

I'll mark this issue as wontfix, since I do not intent to fiddle with the autotools setup unless absolutely necessary and this will eventually fixed by using a different build tool.

**Comment by SpotlightKid** [comment]
So, after the new `meson` based build / installation setup is done, the Python modules still get installed into `/usr/lib/python3.x/site-packages/`, which is not in `sys.path` on debian/Ubuntu.

I've spoken to Ubuntu packagers because I think it is the responsibility of debian / Ubuntu to fix their Python installation, so that it reports the right module installation paths in a way that meson can detect, but they told me, that their packaging system takes care of that and that they don't support software not installed via their package management. This leaves us with either fixing meson to handle Python module installation specially on Ubuntu or implementing our own workarounds.

I'm inclined to *not* do the latter and just declare installation from source or a Git repo checkout as unsupported on debian / Ubuntu (and derivatives). Nevertheless, I have created a page on the `jack_mixer` GitHub wiki, that describes, how this can be achieved with some manual editing of the `jack_mixer` start script:

https://github.com/jack-mixer/jack_mixer/wiki/Installing-on-debian---Ubuntu

And with that I'll close this ticket and refer everyone experiencing this problem to either the official debian / Ubuntu packages or the mentioned wiki page.
