### ISSUE TITLE
Freezes when attempting to save a mixer

### ISSUE THREAD

**Issue by eeickmeyer** [jack-mixer/jack_mixer#7]
Steps to reproduce:

1. Open, add mixer strips
2. Attempt to save session with any filename.
3. Detaches from Jack and becomes nonresponsive

```
/usr/bin/jack_mixer:273: PyGTKDeprecationWarning: The "buttons" argument must be a Gtk.ButtonsType enum value. Please use the "add_buttons" method for adding buttons. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  dlg = Gtk.FileChooserDialog(title='Save', parent=self.window,
SuspendRefNum error
JackClient::Execute error name = jack_mixer
Traceback (most recent call last):
  File "/usr/bin/jack_mixer", line 280, in on_save_as_cb
    self.on_save_cb()
  File "/usr/bin/jack_mixer", line 268, in on_save_cb
    f = file(self.current_filename, 'w')
NameError: name 'file' is not defined
```

**Comment by frederic-peters** [comment]
Hi! This was a compatibility problem with Python 3; it has been fixed in release 12 (specifically, commit 03d5ebdb).
